[package]
name = "lucid-dreams"
version = "0.1.0"
authors = ["Shayne Fitzgerald <robotech417@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy_strings = "0.2"